### ISSUE TITLE
FirstVoices Language Learning Enhancements

### ISSUE THREAD

**Issue by bcdevex** [First-Peoples-Cultural-Council/fv-web-ui#127]
<p>This issue has been auto-generated to facilitate questions about
<a href="https://bcdevexchange.org/opportunities/cwu/opp-firstvoices-language-learning-enhancements"> a paid opportunity</a> that has just been posted on the
<a href="https://bcdevexchange.org">BCDevExchange</a>.</p>

<p>To learn more or apply, <a href="https://bcdevexchange.org/opportunities/cwu/opp-firstvoices-language-learning-enhancements">visit the opportunity page</a>.
The opportunity closes on <b>Thursday, January 16th, 2020 at 16:00 PST</b>.</p>

**Comment by jwhannis** [comment]
Hi:

We have a few questions about the opportunity.

1) Is there a product owner and/or scrum master assigned to the project? We're assuming an Agile project management methodology is being used.  Essentially, is there a process in place to facilitate requirements clarification and feature/scope creep?

2) How were the milestones scoped?  Was there an estimation process that occurred to come up with the timeframes and budgets?

3) What is the user acceptance testing capabilities and process for the project?

**Comment by sludlow-regroove** [comment]
Hello! We also have some questions about this project (and agree with the questions above from jwhannis);

1. Quickly looking through the code base, it looks to be well documented. However, it's not noted whether the site is built using only custom code or on top of an existing CMS?

2. The milestones seem be be mostly front-end work, but there are a couple that are creating entire new features. Does this include creating new API functions etc, or has work already been done to the back-end to set up what's needed? Some wording of 'Develop UI for ...' makes me assume that we'd be _interacting_ with the back-end and less creating and adjusting new features.

We'd also just like to say thank you very much for your time writing a clear and well broken-down CWU statement, it's one of the clearest we've seen and it's appreciated.

**Comment by dy2288** [comment]
Hi @jwhannis -
Thank you for the questions.

> _Is there a product owner and/or scrum master assigned to the project? We're assuming an Agile project management methodology is being used. Essentially, is there a process in place to facilitate requirements clarification and feature/scope creep?_

We do not have an officially trained Scrum Master or Product Owner, however our FirstVoices Coordinator/Trainer is very well positioned to make product decisions.

Our expectation is that as part of the proposal, the successful candidate will recommend a process that has worked for them in the past on similar projects. They should have good project management skills, communication skills, and decide on how to get consensus on wireframes, prototypes or designs as part of the proposal. We are aware of feature and scope creep and will do our part to make sure it does not hinder the project. 

> _How were the milestones scoped? Was there an estimation process that occurred to come up with the timeframes and budgets?_

In order to come up with the milestone details we did user-research with our target audience, and an environmental scan of other, similar language learning tools. The estimation process was based on what we think a capable full-stack developer should be able to do in the timeframe, especially when reusing functionality that exists in the platform.

> _What is the user acceptance testing capabilities and process for the project?_

Our lead will available to do UAT throughout the project to sign off on deployed features. Near the end of every milestone we will expect a demo/walkthrough of the milestone with opportunity for feedback.

> _How detailed is the design and requirements for the requested features/improvements?_

The level of detail that is in our opportunity. We've also provided some links to inspiration when the features are not self-explanatory. Aside from that, the designs should fit well within FirstVoices.com and use Material UI when possible/appropriate. We have a design guide that details typography, colours, spacing, etc.

> _Are resources available (ie. team lead or technical architect) to provide knowledge transfer to the successful vendor?_

Yes. I'm the technical lead for the project. We also have a front-end lead that will provide knowledge transfer at the beginning of the project, and to a lesser degree throughout the project (i.e. pointing a knowledgeable developer to the right places, as opposed to troubleshooting together). Please also note that our repo will not be frozen, so small, frequent commits may be preferable to large, less frequent commits.

**Comment by dy2288** [comment]
> Hello! We also have some questions about this project (and agree with the questions above from jwhannis);
> 
> 1. Quickly looking through the code base, it looks to be well documented. However, it's not noted whether the site is built using only custom code or on top of an existing CMS?
> 2. The milestones seem be be mostly front-end work, but there are a couple that are creating entire new features. Does this include creating new API functions etc, or has work already been done to the back-end to set up what's needed? Some wording of 'Develop UI for ...' makes me assume that we'd be _interacting_ with the back-end and less creating and adjusting new features.

Hi @sludlow-regroove -
Thanks for the comment.

1. The site is built on Nuxeo CMS (see https://www.nuxeo.com/ and https://github.com/nuxeo/nuxeo), which the front-end custom code (`frontend` folder), interacts with. Back-end code (e.g. `FirstVoicesEnrichers` folder) extends Nuxeo via OSGI-compliant modules.

2. Although the opportunity is heavy on the UI, back-end end-points / API functions may be necessary to complete some of these tasks. Nuxeo provides fairly straightforward ways to extend the API though, with clear documentation: https://doc.nuxeo.com/nxdoc/contributing-an-operation/

**Comment by bcdevex** [comment]
This opportunity has been assigned

**Comment by kyrafortier** [comment]
Dear Applicants,
Our sincere thanks for the effort you put into your proposals. We received a total of ten proposals. This was a competitive opportunity. Based on our evaluation criteria, we have selected @sludlow-regroove for this opportunity. We are confident this will be a successful partnership.
We look forward to working with other applicants in the future. Please contact us privately for feedback on your proposals. I can be reached at kyra@fpcc.ca.
All the best,
Kyra Fortier

**Comment by kyrafortier** [comment]
We have accepted Phase 1 into our master branch and are excited to get this feature to our users in the next release. We have mutually agreed to end the opportunity prior to Phase 2 and 3. Anyone wishing to follow up with us can do so via email kyra@fpcc.ca

Kyra Fortier
